// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnI4a3PMRMgdX3615XO4A4KtsoMRFiL24',
    appId: '1:42084414849:android:0adf6846a92d3bce6b2480',
    messagingSenderId: '42084414849',
    projectId: 'random-waifu',
    databaseURL: 'https://random-waifu.firebaseio.com',
    storageBucket: 'random-waifu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDGcapinAx5zblC8gX5VTcu-SLfY6dHH4',
    appId: '1:42084414849:ios:09a781fcea5e0a216b2480',
    messagingSenderId: '42084414849',
    projectId: 'random-waifu',
    databaseURL: 'https://random-waifu.firebaseio.com',
    storageBucket: 'random-waifu.appspot.com',
    androidClientId: '42084414849-7i2s0eidp6drevg334ee8dsdphkjtmbn.apps.googleusercontent.com',
    iosClientId: '42084414849-djsppa4bg0quhhpanda7kpekn30h5qmh.apps.googleusercontent.com',
    iosBundleId: 'com.logic.randomWaifu',
  );
}
